package com.greenhouse.backend.audit.domain;

public enum AuditSource {
	ORCHID_GROUP_CORRECTION,
	ORCHID_GROUP_MANAGEMENT,
	VARIETY_MANAGEMENT,
	INBOUND_MANAGEMENT,
	ORCHID_GROUP_COLLECTION,
	FARM_STRUCTURE_MANAGEMENT,
	PARTNER_MANAGEMENT,
	SALES_MANAGEMENT,
	SETTLEMENT_MANAGEMENT,
	WORK_RECORD,
	DATA_MIGRATION,
	SYSTEM
}
