#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate final-schema PostgreSQL seed SQL for auction shipment/result tracking.

This script reuses the pre-migration domain-building logic from auction_domain.py,
but emits SQL for the final schema:
- auction_shipments.auction_market is not used.
- auction_shipments.auction_house_id references business_partners(id).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from auction_domain import (
    LOT_STATUS_WAITING,
    Shipment,
    Lot,
    Attempt,
    ResultLine,
    StatusHistory,
    ReviewIssue,
    build_domain,
    normalize_row,
    read_csv_rows,
    sql_literal,
    write_review_csv,
)
from seed_common import normalize_market, values_rows

TABLE_SHIPMENTS = "auction_shipments"
TABLE_LOTS = "auction_shipment_lots"
TABLE_ATTEMPTS = "auction_attempts"
TABLE_RESULT_LINES = "auction_result_lines"
TABLE_STATUS_HISTORY = "auction_lot_status_history"


def partner_id_subquery(market: str) -> str:
    return (
        "(SELECT MIN(id) FROM business_partners "
        "WHERE partner_type = 'AUCTION_HOUSE' "
        f"AND LOWER(name) = LOWER({sql_literal(market)}))"
    )


def generate_partner_guard_sql(markets: list[str]) -> str:
    lines: list[str] = []
    if not markets:
        return ""
    lines.append("-- Ensure auction houses exist as business partners for the final schema.")
    lines.append("INSERT INTO business_partners (")
    lines.append("    created_at, updated_at, name, partner_type, is_active, memo")
    lines.append(")")
    lines.append("SELECT")
    lines.append("    CURRENT_TIMESTAMP,")
    lines.append("    CURRENT_TIMESTAMP,")
    lines.append("    seed.name,")
    lines.append("    'AUCTION_HOUSE',")
    lines.append("    TRUE,")
    lines.append("    '경매 seed 데이터용 거래처'")
    lines.append("FROM (VALUES")
    lines.append(values_rows([(market,) for market in markets], indent="    "))
    lines.append(") AS seed(name)")
    lines.append("WHERE NOT EXISTS (")
    lines.append("    SELECT 1")
    lines.append("    FROM business_partners partner")
    lines.append("    WHERE partner.partner_type = 'AUCTION_HOUSE'")
    lines.append("      AND LOWER(partner.name) = LOWER(seed.name)")
    lines.append(");")
    lines.append("")
    return "\n".join(lines)


def generate_sql(
    input_file: Path,
    normalized_rows: list,
    shipments: list[Shipment],
    lots: list[Lot],
    attempts: list[Attempt],
    result_lines: list[ResultLine],
    status_histories: list[StatusHistory],
    include_truncate: bool,
    ensure_partners: bool,
) -> str:
    now_expr = "CURRENT_TIMESTAMP"
    markets = sorted({normalize_market(s.market) for s in shipments if s.market})
    lines: list[str] = []
    lines.append("-- Generated by generate_auction_seed.py")
    lines.append("-- Final schema: auction_shipments.auction_house_id -> business_partners(id)")
    lines.append(f"-- Source file: {input_file.name}")
    lines.append(f"-- Source rows: {len(normalized_rows)}")
    lines.append(
        f"-- Shipments: {len(shipments)}, Lots: {len(lots)}, Attempts: {len(attempts)}, "
        f"Result lines: {len(result_lines)}, Status histories: {len(status_histories)}"
    )
    lines.append("BEGIN;")
    lines.append("")

    if include_truncate:
        lines.append("-- WARNING: This removes existing auction seed data. Do not use in normal Flyway migration seeds.")
        lines.append(
            "TRUNCATE TABLE "
            f"{TABLE_RESULT_LINES}, {TABLE_ATTEMPTS}, {TABLE_STATUS_HISTORY}, {TABLE_LOTS}, {TABLE_SHIPMENTS} "
            "RESTART IDENTITY CASCADE;"
        )
        lines.append("")

    if ensure_partners:
        lines.append(generate_partner_guard_sql(markets))

    if shipments:
        lines.append(
            f"INSERT INTO {TABLE_SHIPMENTS} "
            "(id, shipment_date, auction_house_id, status, memo, created_at, updated_at) VALUES"
        )
        lines.append(",\n".join(
            f"  ({s.id}, {sql_literal(s.shipment_date)}, {partner_id_subquery(normalize_market(s.market))}, "
            f"{sql_literal(s.status)}, {sql_literal(s.memo)}, {now_expr}, {now_expr})"
            for s in shipments
        ) + ";")
        lines.append("")

    if lots:
        lines.append(
            f"INSERT INTO {TABLE_LOTS} "
            "(id, shipment_id, item_name, variety_name, shipment_grade, boxes, shipped_quantity, "
            "sold_quantity, waiting_quantity, returned_quantity, current_status, memo, created_at, updated_at) VALUES"
        )
        lines.append(",\n".join(
            f"  ({lot.id}, {lot.shipment.id}, {sql_literal(lot.item_name)}, {sql_literal(lot.variety_name)}, "
            f"{sql_literal(lot.grade)}, {sql_literal(lot.boxes)}, {lot.shipped_quantity}, {lot.sold_quantity}, "
            f"{lot.waiting_quantity}, {lot.returned_quantity}, {sql_literal(lot.current_status)}, "
            f"{sql_literal(lot.memo)}, {now_expr}, {now_expr})"
            for lot in lots
        ) + ";")
        lines.append("")

    if attempts:
        lines.append(
            f"INSERT INTO {TABLE_ATTEMPTS} "
            "(id, shipment_lot_id, auction_date, attempt_no, attempt_status, failed_reason, memo, created_at, updated_at) VALUES"
        )
        lines.append(",\n".join(
            f"  ({a.id}, {a.lot.id}, {sql_literal(a.auction_date)}, {a.attempt_no}, "
            f"{sql_literal(a.status)}, {sql_literal(a.failed_reason)}, {sql_literal(a.memo)}, {now_expr}, {now_expr})"
            for a in attempts
        ) + ";")
        lines.append("")

    if result_lines:
        lines.append(
            f"INSERT INTO {TABLE_RESULT_LINES} "
            "(id, auction_attempt_id, auction_date, auction_grade, quantity, unit_price, amount, note, "
            "inspection_status, created_at, updated_at) VALUES"
        )
        lines.append(",\n".join(
            f"  ({line.id}, {line.attempt.id}, {sql_literal(line.row.auction_date)}, {sql_literal(line.row.grade)}, "
            f"{line.row.quantity}, {line.row.unit_price}, {line.row.amount}, {sql_literal(line.row.note)}, "
            f"{sql_literal(line.inspection_status)}, {now_expr}, {now_expr})"
            for line in result_lines
        ) + ";")
        lines.append("")

    if status_histories:
        lines.append(
            f"INSERT INTO {TABLE_STATUS_HISTORY} "
            "(id, changed_at, reason, new_status, previous_status, memo, worker, shipment_lot_id) VALUES"
        )
        lines.append(",\n".join(
            f"  ({h.id}, {sql_literal(h.changed_at)}, {sql_literal(h.reason)}, {sql_literal(h.new_status)}, "
            f"{sql_literal(h.previous_status)}, {sql_literal(h.memo)}, {sql_literal(h.worker)}, {h.lot.id})"
            for h in status_histories
        ) + ";")
        lines.append("")

    lines.append("-- Keep bigserial sequences after explicit IDs.")
    for table, count in [
        (TABLE_SHIPMENTS, len(shipments)),
        (TABLE_LOTS, len(lots)),
        (TABLE_ATTEMPTS, len(attempts)),
        (TABLE_RESULT_LINES, len(result_lines)),
        (TABLE_STATUS_HISTORY, len(status_histories)),
    ]:
        if count > 0:
            lines.append(
                f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
                f"GREATEST((SELECT COALESCE(MAX(id), 1) FROM {table}), {count}), true);"
            )
    lines.append("")
    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate auction seed SQL from CSV for final schema.")
    parser.add_argument("--input", required=True, type=Path, help="Source auction CSV path")
    parser.add_argument("--output", required=True, type=Path, help="Output SQL path")
    parser.add_argument("--review", type=Path, default=Path("auction_seed_review_required.csv"), help="Review CSV path")
    parser.add_argument("--truncate", action="store_true", help="Add TRUNCATE for dev reset. Avoid in Flyway migration seeds.")
    parser.add_argument("--no-ensure-partners", action="store_true", help="Do not emit business_partners guard insert block")
    args = parser.parse_args()

    source_rows = read_csv_rows(args.input)
    normalized_rows = []
    normalize_errors: list[ReviewIssue] = []
    for source in source_rows:
        try:
            normalized_rows.append(normalize_row(source))
        except Exception as exc:
            normalize_errors.append(ReviewIssue(
                row_number=source.row_number,
                issue_type="SOURCE_ERROR",
                message=str(exc),
                raw=source.raw,
            ))

    shipments, lots, attempts, result_lines, status_histories, reviews = build_domain(normalized_rows)
    reviews = normalize_errors + reviews

    sql = generate_sql(
        args.input,
        normalized_rows,
        shipments,
        lots,
        attempts,
        result_lines,
        status_histories,
        include_truncate=args.truncate,
        ensure_partners=not args.no_ensure_partners,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")
    args.review.parent.mkdir(parents=True, exist_ok=True)
    write_review_csv(args.review, reviews)

    shipment_count = sum(1 for r in normalized_rows if r.row_type == "SHIPMENT")
    auction_count = sum(1 for r in normalized_rows if r.row_type == "AUCTION")
    print("Generated:", args.output)
    print("Review CSV:", args.review)
    print(f"Rows: total={len(source_rows)}, normalized={len(normalized_rows)}, shipment={shipment_count}, auction={auction_count}")
    print(
        f"Domain: shipments={len(shipments)}, lots={len(lots)}, attempts={len(attempts)}, "
        f"result_lines={len(result_lines)}, status_histories={len(status_histories)}"
    )
    print(f"Review issues: {len(reviews)}")


if __name__ == "__main__":
    main()
