#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate business partner master-data seed SQL from auction/direct sales sources."""

from __future__ import annotations

import argparse
from pathlib import Path

from seed_common import (
    SeedPartner,
    clean_text,
    normalize_market,
    partner_type_for_direct_sale,
    read_csv_dicts,
    row_value,
    sql_literal,
    values_rows,
)


def collect_auction_partners(auction_csv: Path | None) -> set[SeedPartner]:
    partners: set[SeedPartner] = set()
    if not auction_csv:
        return partners
    for row in read_csv_dicts(auction_csv):
        market = normalize_market(row_value(row, "경매장", "auctionMarket", "market"))
        if market:
            partners.add(SeedPartner(market, "AUCTION_HOUSE", "초기 경매 데이터 거래처"))
    return partners


def collect_direct_partners(direct_csv: Path | None) -> set[SeedPartner]:
    partners: set[SeedPartner] = set()
    if not direct_csv:
        return partners
    for row in read_csv_dicts(direct_csv):
        name = clean_text(row_value(row, "구매자명", "거래처명", "partnerName", "customerName"))
        if not name:
            continue
        partners.add(SeedPartner(name, partner_type_for_direct_sale(name), "초기 일반 판매 데이터 거래처"))
    return partners


def resolve_partner_conflicts(partners: set[SeedPartner]) -> list[SeedPartner]:
    # Same visible name should be represented once. AUCTION_HOUSE wins, then RETAIL, then WHOLESALE.
    priority = {"AUCTION_HOUSE": 3, "RETAIL": 2, "WHOLESALE": 1}
    by_key: dict[str, SeedPartner] = {}
    for partner in partners:
        key = clean_text(partner.name).casefold()
        current = by_key.get(key)
        if current is None or priority.get(partner.partner_type, 0) > priority.get(current.partner_type, 0):
            by_key[key] = partner
    return sorted(by_key.values(), key=lambda p: (p.partner_type, p.name))


def generate_sql(partners: list[SeedPartner], source_names: list[str]) -> str:
    lines: list[str] = []
    lines.append("-- Generated by generate_business_partners_seed.py")
    lines.append("-- Source files: " + ", ".join(source_names))
    lines.append(f"-- Business partners: {len(partners)}")
    lines.append("BEGIN;")
    lines.append("")

    lines.append("CREATE TEMP TABLE _seed_business_partners (")
    lines.append("    name TEXT NOT NULL,")
    lines.append("    partner_type TEXT NOT NULL,")
    lines.append("    memo TEXT")
    lines.append(") ON COMMIT DROP;")
    lines.append("")

    if partners:
        rows = [(p.name, p.partner_type, p.memo) for p in partners]
        lines.append("INSERT INTO _seed_business_partners (name, partner_type, memo) VALUES")
        lines.append(values_rows(rows) + ";")
        lines.append("")

        lines.append("INSERT INTO business_partners (")
        lines.append("    created_at, updated_at, name, partner_type, is_active, memo")
        lines.append(")")
        lines.append("SELECT")
        lines.append("    CURRENT_TIMESTAMP,")
        lines.append("    CURRENT_TIMESTAMP,")
        lines.append("    seed.name,")
        lines.append("    seed.partner_type,")
        lines.append("    TRUE,")
        lines.append("    seed.memo")
        lines.append("FROM _seed_business_partners seed")
        lines.append("WHERE NOT EXISTS (")
        lines.append("    SELECT 1 FROM business_partners partner")
        lines.append("    WHERE LOWER(partner.name) = LOWER(seed.name)")
        lines.append(");")
        lines.append("")

        lines.append("UPDATE business_partners partner")
        lines.append("SET")
        lines.append("    partner_type = seed.partner_type,")
        lines.append("    is_active = TRUE,")
        lines.append("    updated_at = CURRENT_TIMESTAMP")
        lines.append("FROM _seed_business_partners seed")
        lines.append("WHERE LOWER(partner.name) = LOWER(seed.name)")
        lines.append("  AND partner.partner_type <> seed.partner_type;")
        lines.append("")

        lines.append("INSERT INTO partner_settlement_settings (")
        lines.append("    created_at,")
        lines.append("    updated_at,")
        lines.append("    allow_prepayment,")
        lines.append("    amount_tolerance,")
        lines.append("    auto_match_enabled,")
        lines.append("    auto_settle_enabled,")
        lines.append("    credit_auto_apply_enabled,")
        lines.append("    depositor_aliases,")
        lines.append("    memo,")
        lines.append("    payment_day_mode,")
        lines.append("    payment_delay_days,")
        lines.append("    rule_json,")
        lines.append("    settlement_unit,")
        lines.append("    partner_id")
        lines.append(")")
        lines.append("SELECT")
        lines.append("    CURRENT_TIMESTAMP,")
        lines.append("    CURRENT_TIMESTAMP,")
        lines.append("    TRUE,")
        lines.append("    0,")
        lines.append("    TRUE,")
        lines.append("    FALSE,")
        lines.append("    TRUE,")
        lines.append("    '[]'::jsonb,")
        lines.append("    '초기 seed 기본 정산 설정',")
        lines.append("    'CALENDAR_DAY',")
        lines.append("    CASE WHEN partner.partner_type = 'AUCTION_HOUSE' THEN 7 ELSE 0 END,")
        lines.append("    '{}'::jsonb,")
        lines.append("    CASE WHEN partner.partner_type = 'AUCTION_HOUSE' THEN 'AUCTION_DATE' ELSE 'SALES_SLIP' END,")
        lines.append("    partner.id")
        lines.append("FROM business_partners partner")
        lines.append("JOIN _seed_business_partners seed ON LOWER(seed.name) = LOWER(partner.name)")
        lines.append("WHERE NOT EXISTS (")
        lines.append("    SELECT 1 FROM partner_settlement_settings setting")
        lines.append("    WHERE setting.partner_id = partner.id")
        lines.append(");")
        lines.append("")

        lines.append("INSERT INTO partner_balance_summaries (")
        lines.append("    created_at,")
        lines.append("    updated_at,")
        lines.append("    credit_balance,")
        lines.append("    receivable_balance,")
        lines.append("    unapplied_payment_amount,")
        lines.append("    partner_id,")
        lines.append("    summary_json,")
        lines.append("    last_payment_event_id")
        lines.append(")")
        lines.append("SELECT")
        lines.append("    CURRENT_TIMESTAMP,")
        lines.append("    CURRENT_TIMESTAMP,")
        lines.append("    0,")
        lines.append("    0,")
        lines.append("    0,")
        lines.append("    partner.id,")
        lines.append("    '{}'::jsonb,")
        lines.append("    NULL")
        lines.append("FROM business_partners partner")
        lines.append("JOIN _seed_business_partners seed ON LOWER(seed.name) = LOWER(partner.name)")
        lines.append("WHERE NOT EXISTS (")
        lines.append("    SELECT 1 FROM partner_balance_summaries summary")
        lines.append("    WHERE summary.partner_id = partner.id")
        lines.append(");")
        lines.append("")

    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate business partner seed SQL from source CSV files.")
    parser.add_argument("--auction-csv", type=Path, help="Auction source CSV")
    parser.add_argument("--direct-csv", type=Path, help="Direct sales source CSV")
    parser.add_argument("--output", required=True, type=Path, help="Output SQL path")
    args = parser.parse_args()

    partners = resolve_partner_conflicts(
        collect_auction_partners(args.auction_csv) | collect_direct_partners(args.direct_csv)
    )
    source_names = [p.name for p in [args.auction_csv, args.direct_csv] if p]
    sql = generate_sql(partners, source_names)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql, encoding="utf-8")

    by_type: dict[str, int] = {}
    for partner in partners:
        by_type[partner.partner_type] = by_type.get(partner.partner_type, 0) + 1
    print("Generated:", args.output)
    print("Business partners:", len(partners), by_type)


if __name__ == "__main__":
    main()
