import type { Material, Variety } from "../model/types";

export const INITIAL_VARIETIES: Variety[] = [
  {
    id: 1,
    code: "CAT-0001",
    genus: "카틀레야",
    name: "카틀레야 A",
    potSize: "4치",
    saleEnabled: true,
    status: "ACTIVE",
    description: "꽃 크기가 크고 색상이 선명하며 개화 기간이 긴 품종입니다.",
    memo: "봄 개화주 관리 주의",
    registeredAt: "2026-01-10",
    updatedAt: "2026-06-20",
    connectedGroups: [
      {
        id: 1,
        location: "1동 - 1배드 좌측",
        quantity: 120,
        status: "정상",
        latestWork: "2026-06-01 (농약)",
      },
      {
        id: 2,
        location: "3동 - 2배드 우측",
        quantity: 80,
        status: "주의",
        latestWork: "2026-05-25 (비료)",
      },
      {
        id: 3,
        location: "5동 - 1배드 좌측",
        quantity: 60,
        status: "이상",
        latestWork: "2026-06-19 (위치 이동)",
      },
      {
        id: 4,
        location: "7동 - 3배드 우측",
        quantity: 40,
        status: "정상",
        latestWork: "2026-06-05 (비료)",
      },
    ],
  },
  {
    id: 2,
    code: "CAT-0002",
    genus: "카틀레야",
    name: "카틀레야 B",
    potSize: "5치",
    saleEnabled: true,
    status: "ACTIVE",
    description: "대형 화형의 카틀레야 품종입니다.",
    memo: "",
    registeredAt: "2026-01-10",
    updatedAt: "2026-04-12",
    connectedGroups: [],
  },
  {
    id: 3,
    code: "DEN-0001",
    genus: "덴드로비움",
    name: "덴드로비움 C",
    potSize: "3.5치",
    saleEnabled: true,
    status: "ACTIVE",
    description: "관리하기 쉬운 덴드로비움 품종입니다.",
    memo: "",
    registeredAt: "2026-01-11",
    updatedAt: "2026-03-18",
    connectedGroups: [],
  },
  {
    id: 4,
    code: "DEN-0002",
    genus: "덴드로비움",
    name: "덴드로비움 D",
    potSize: "3치",
    saleEnabled: false,
    status: "INACTIVE",
    description: "시험 재배 후 비활성 처리된 품종입니다.",
    memo: "판매 중단",
    registeredAt: "2026-02-05",
    updatedAt: "2026-05-02",
    connectedGroups: [],
  },
  {
    id: 5,
    code: "SYM-0001",
    genus: "심비디움",
    name: "심비디움 E",
    potSize: "5.5치",
    saleEnabled: true,
    status: "ACTIVE",
    description: "겨울철 출하용 심비디움 품종입니다.",
    memo: "",
    registeredAt: "2026-01-12",
    updatedAt: "2026-05-11",
    connectedGroups: [],
  },
  {
    id: 6,
    code: "PHA-0001",
    genus: "팔레놉시스",
    name: "호접란 F",
    potSize: "2.5치",
    saleEnabled: true,
    status: "ACTIVE",
    description: "소형 선물용 호접란입니다.",
    memo: "",
    registeredAt: "2026-01-12",
    updatedAt: "2026-05-14",
    connectedGroups: [],
  },
  {
    id: 7,
    code: "ONC-0001",
    genus: "온시디움",
    name: "온시디움 G",
    potSize: "3치",
    saleEnabled: true,
    status: "ACTIVE",
    description: "황색 꽃이 풍성하게 피는 품종입니다.",
    memo: "",
    registeredAt: "2026-01-13",
    updatedAt: "2026-06-01",
    connectedGroups: [],
  },
  {
    id: 8,
    code: "VAN-0001",
    genus: "반다",
    name: "반다 H",
    potSize: "3치",
    saleEnabled: true,
    status: "ACTIVE",
    description: "통풍과 습도 관리가 중요한 품종입니다.",
    memo: "",
    registeredAt: "2026-01-14",
    updatedAt: "2026-06-03",
    connectedGroups: [],
  },
];

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 1,
    code: "CHE-0001",
    category: "농약",
    name: "더블엑스",
    manufacturer: "(주)한밭농",
    specification: "500ml",
    stockQuantity: "1000ml",
    storageLocation: "자재실 상단 선반",
    usage: "예방 및 치료용 살포",
    status: "ACTIVE",
    registeredAt: "2026-01-05",
  },
  {
    id: 2,
    code: "CHE-0002",
    category: "농약",
    name: "오티바",
    manufacturer: "신젠타코리아",
    specification: "250ml",
    stockQuantity: "500ml",
    storageLocation: "자재실 상단 선반",
    usage: "살균제",
    status: "ACTIVE",
    registeredAt: "2026-01-05",
  },
  {
    id: 3,
    code: "FER-0001",
    category: "비료",
    name: "하이그로 20-20-20",
    manufacturer: "(주)농배화학",
    specification: "1kg",
    stockQuantity: "3kg",
    storageLocation: "자재실 하단 선반",
    usage: "생육기 액비",
    status: "ACTIVE",
    registeredAt: "2026-01-06",
  },
  {
    id: 4,
    code: "FER-0002",
    category: "비료",
    name: "개화 촉진제",
    manufacturer: "그린팜",
    specification: "500g",
    stockQuantity: "1kg",
    storageLocation: "자재실 하단 선반",
    usage: "개화 전 사용",
    status: "ACTIVE",
    registeredAt: "2026-02-10",
  },
  {
    id: 5,
    code: "SUP-0001",
    category: "자재",
    name: "난 전용 화분",
    manufacturer: "우리화분",
    specification: "4치 / 100개",
    stockQuantity: "240개",
    storageLocation: "창고 2번 랙",
    usage: "분갈이",
    status: "INACTIVE",
    registeredAt: "2026-03-02",
  },
];
