import type { Material } from "../model/types";

export const INITIAL_MATERIALS: Material[] = [
  {
    id: 1,
    code: "CHE-0001",
    category: "농약",
    name: "더블엑스",
    manufacturer: "(주)한밭농",
    specification: "500ml",
    stockQuantity: "1000ml",
    storageLocation: "자재실 상단 선반",
    usage: "예방 및 치료용 살포",
    status: "ACTIVE",
    registeredAt: "2026-01-05",
  },
  {
    id: 2,
    code: "CHE-0002",
    category: "농약",
    name: "오티바",
    manufacturer: "신젠타코리아",
    specification: "250ml",
    stockQuantity: "500ml",
    storageLocation: "자재실 상단 선반",
    usage: "살균제",
    status: "ACTIVE",
    registeredAt: "2026-01-05",
  },
  {
    id: 3,
    code: "FER-0001",
    category: "비료",
    name: "하이그로 20-20-20",
    manufacturer: "(주)농배화학",
    specification: "1kg",
    stockQuantity: "3kg",
    storageLocation: "자재실 하단 선반",
    usage: "생육기 액비",
    status: "ACTIVE",
    registeredAt: "2026-01-06",
  },
  {
    id: 4,
    code: "FER-0002",
    category: "비료",
    name: "개화 촉진제",
    manufacturer: "그린팜",
    specification: "500g",
    stockQuantity: "1kg",
    storageLocation: "자재실 하단 선반",
    usage: "개화 전 사용",
    status: "ACTIVE",
    registeredAt: "2026-02-10",
  },
  {
    id: 5,
    code: "SUP-0001",
    category: "자재",
    name: "난 전용 화분",
    manufacturer: "우리화분",
    specification: "4치 / 100개",
    stockQuantity: "240개",
    storageLocation: "창고 2번 랙",
    usage: "분갈이",
    status: "INACTIVE",
    registeredAt: "2026-03-02",
  },
];
