package com.greenhouse.backend.auction.domain;

public enum AuctionLotStatus {
	SHIPPED,
	WAITING,
	IN_PROGRESS,
	SOLD,
	PARTIALLY_SOLD,
	FAILED,
	REAUCTION_WAITING,
	RETURN_INFERRED,
	PARTIALLY_RETURNED,
	RETURNED,
	QUANTITY_MISMATCH,
	REVIEW_REQUIRED,
	CANCELLED
}
