package com.greenhouse.backend.settlement.domain;

public enum PaymentEventType {
	PAYMENT_RECEIVED,
	PAYMENT_ALLOCATED,
	PREPAYMENT_RECEIVED,
	CREDIT_APPLIED,
	CREDIT_REFUND,
	AUTO_MATCH_CANDIDATE,
	AUTO_MATCH_CONFIRMED,
	MANUAL_MATCH_CONFIRMED,
	MATCH_REJECTED,
	PAYMENT_UNLINKED,
	ADJUSTMENT
}
