apiVersion: v1
kind: Service
metadata:
  name: green-house-frontend
  namespace: green-house
  labels:
    app.kubernetes.io/name: green-house
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: green-house
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
